export default {
    Antibiotics: [
        "Amoxicillin",
        "Chloramphenicol",
        "Neomycin",
        "Silver Sulfadiazine",
        "Trimethoprim",
        "Sulfadoxine",
        "Cephalexin",
        "Cefovecin",
        "Cefpodoxime",
        "Ceftiofur",
        "Ciprofloxacin",
        "Clavamox",
        "Clavaseptin",
        "Clavulanic Acid",
        "Clindamycin",
        "Doxycycline",
        "Enrofloxacin",
        "Marbofloxacin",
        "Metronidazole",
        "Moxifloxacin",
        "Ofloxacin",
        "Oxytetracycline",
        "Streptomycin",
        "Thiostrepton",
        "Tylosin",
        "rifampin",
        "pirlimycin",
        "dichlorophene",
        "Aminoglycosides",
        "ß-Lactam Antibiotics",
        "Chloramphenicol",
        "Fluoroquinolones",
        "Glycopeptides",
        "Lincosamides",
        "Macrolides",
        "Polymixins",
        "Rifamycins",
        "Streptogramins",
        "Tetracyclines",
        "Diaminopyrimidines",
    ],
    Analgesics: [
        "Tramadol",
        "Oxymorphone",
        "Morphine",
        "Medetomidine",
        "Hydromorphone",
        "Flunixin Meglumine",
        "Atipamezole",
        "Amantadine",
        "Chloral Hydrate",
        "Magnesium Sulfate",
        "Pentobarbital",
        "Bupivacaine",
        "Ketamine",
        "Propofol",
        "Telazol",
        "Anesthesia",
        "Pregabalin",
        "Gabapentin",
        "Metacam",
        "Carprofen",
        "Buprenorphine",
        "Bethanechol",
    ],
    Medicines: [
        "Calcium Borogluconate 23% Canada",
        "Calcium Drench Plus Vitamins",
        "Calcium Drench with Vitamins",
        "Calcium Gel",
        "Calcium Gluconate 23%",
        "Calcium Gluconate 23% Injection Canada",
        "Calcium Gluconate 23% Solution",
        "Calcium Gluconate 23% Solution, USP",
        "Calcium Injection",
        "Calcium Phosphorus Powder",
        "Calcium Phosphorus Powder Canada",
        "Calcium Phosphorus Tablets",
        "Calcium Phosphorus Tablets Canada",
        "A O E All Purpose Deodorizing Pet Wipes",
        "A O E All Purpose Deodorizing Pet Wipes Canada",
        "A O E, Animal Odor Eliminator",
        "A O E, Animal Odor Eliminator Canada",
        "A-Cyst",
        "A-Lyte Concentrate",
        "A-Lyte Solution",
        "A180 Canada",
        "Ab Select - AVe Equine HI Plasma",
        "Ab Select - AVw Equine HI Plasma",
        "Abelia MalaOtic",
        "Abelia Small Pet Otic",
        "Abelia TrisOtic",
        "Absolution Pg",
        "Absorbine B-L Pellets Canada",
        "Absorbine B-L Solution Canada",
        "Absorbine Flex+Max Joint Health Supplement Pellets Canada",
        "Absorbine Flys-X Livestock Ready to Use Insecticide",
        "Absorbine Fungasol Ointment",
        "Absorbine Fungasol Shampoo",
        "Absorbine Fungasol Spray",
        "Absorbine Hooflex Liquid Conditioner",
        "Absorbine Hooflex Natural Dressing + Conditioner",
        "Absorbine Hooflex Therapeutic Conditioner Original Conditioner",
        "Absorbine Hooflex Thrush Remedy",
        "Absorbine Pro-Pell Canada",
        "Absorbine ProCMC",
        "Absorbine ShowSheen 2-in-1 Shampoo & Conditioner",
        "Absorbine ShowSheen Detangler Gel",
        "Absorbine ShowSheen Hair Polish & Detangler",
        "Absorbine ShowSheen Miracle Groom Bath in a Bottle Canada",
        "Absorbine ShowSheen Stain Remover & Whitener",
        "Absorbine Silver Honey Ointment Skin Care Canada",
        "Absorbine Silver Honey Spray Skin Care Canada",
        "Absorbine SuperShine Black Hoof Polish",
        "Absorbine SuperShine Clear Hoof Polish",
        "Absorbine UltraShield EX Insecticide & Repellent",
        "Absorbine UltraShield EX Insecticide & Repellent for Horses Canada",
        "Absorbine UltraShield Red Insecticide & Repellent",
        "Absorbine Veterinary Liniment",
        "Absorbine Veterinary Liniment Canada",
        "Absorbine Veterinary Liniment Gel",
        "Absorbine Veterinary Liniment Gel Canada",
        "Accel Health & Wellness Formula",
        "Accel Lifetime Health & Wellness Formula",
        "AccuLytes Complete Electrolyte Formula",
        "Ace Canada",
        "AceproJect",
        "Acepromazine Injection",
        "Acepromazine maleate Injection",
        "Acepromazine maleate Tablets",
        "Acepromazine Tablets",
        "AceproTabs",
        "Acetylator",
        "Aches & Discomfort Support for Cats",
        "Aches & Discomfort Support for Dogs",
        "Achieve Canada",
        "Achieve Calf Milk Replacer Canada",
        "Acid Tray Wash EVO",
        "Acid-A-Foam EVO",
        "Acti-Flex",
        "Acti-Flex K9",
        "Acti-Flex K9 Platinum Hip and Joint Chews",
        "Acti-Flex Pellets",
        "Acti-Flex Powder",
        "Acti-Flex Senior",
        "Actistatin Canine Large Dog Soft Chew",
        "Actistatin Canine Small Bites Small Dog Soft Chew",
        "Actistatin Equine",
        "Activated Charcoal Paste Canada",
        "Activated Clay Gel",
        "Active Again",
        "Activon Tube Canada",
        "Activyl for Cats",
        "Activyl for Cats & Kittens",
        "Activyl for Dogs & Puppies",
        "Activyl Protector Band For Dogs",
        "Activyl TickPlus for Dogs and Puppies",
        "Actogain 100 Canada",
        "Actogain 45",
        "Adams 3-Way Ointment for Dogs",
        "Adams Behavior Control Therapy for Cats & Kittens",
        "Adams Carpet Powder",
        "Adams Ear Mite Treatment",
        "Adams Flea & Tick Cleansing Shampoo",
        "Adams Flea & Tick Cleansing Shampoo for Cats",
        "Adams Flea & Tick Collar for Dogs",
        "lphabetical",
        "B ComplexVET",
        "B-Kalm Supplement Paste",
        "B-Vite Canada",
        "B-Vite Plus Canada",
        "B.B. Jell-Udder Balm Canada",
        "Baby Pig Restart",
        "Baby Pig Restart APF",
        "Baby Pig Restart APF Canada",
        "Bac-Drop Udder Wash",
        "Bach Flowers for Pets Consolation Canada",
        "Bach Flowers for Pets Courage Canada",
        "Bach Flowers for Pets Harmony Canada",
        "Bach Flowers for Pets Quietude Canada",
        "Bacillus CoagulansVET",
        "Bacitracin MD Canada",
        "Back Rubbing Solution Canada",
        "Back-Off Canada",
        "Backflush",
        "BackLine Pour-On Insecticide Canada",
        "Backyard Chicken Oxy E-100",
        "Backyard Chicken Zyfend A",
        "Bactracillin G",
        "Bactracillin G Benzathine",
        "Bag Balm Ointment",
        "Bag Balm Pet",
        "Bar Somnus 2P",
        "Bar-Vac 7",
        "Bar-Vac 7/Somnus",
        "Bar-Vac 8",
        "Bar-Vac CD",
        "Bar-Vac CD/T",
        "Barehoofin",
        "Bark 5 Canada",
        "Barn-Storm Iodine Cleaner Sanitizer Canada",
        "Barnstorm",
        "Barricade Canada",
        "Barrier II Wound Care Spray",
        "Barrier Wound Care Spray",
        "BaseLyte Liquid",
        "Bathless Spray Wash",
        "Baycox (toltrazuril) 5% Oral Suspension Canada",
        "Baytril (enrofloxacin) Antibacterial Injectable Solution 2.27% for dogs",
        "Baytril (enrofloxacin) Antibacterial Tablets",
        "Baytril (enrofloxacin) Antibacterial Taste Tabs",
        "Baytril 100 Canada",
        "Baytril 100 (enrofloxacin) 100 mg/mL Antimicrobial Injectable Solution",
        "Baytril 100-CA1 (enrofloxacin) 100 mg/mL Antimicrobial Injectable Solution",
        "Baytril Flavoured Tablets (15 mg) Canada",
        "Baytril Flavoured Tablets (150 mg) Canada",
        "Baytril Flavoured Tablets (50 mg) Canada",
        "Baytril Injectable Solution Canada",
        "Baytril Otic Canada",
        "Baytril Otic Antibacterial-Antimycotic Emulsion",
        "Bayvarol Canada",
        "BDA Blen",
        "Be Green Doktor Doom Premium Fresh Water Diatomaceous Earth Insect Killer (Commercial) Canada",
        "Beetle Shield 6",
        "Bell's Cattle Cathartic Canada",
        "Benasoothe Conditioner",
        "Benasoothe Shampoo",
        "Bene-Bac Plus Pet Gel",
        "Bene-Bac Plus Pet Gel Canada",
        "Bene-Bac Plus Powder",
        "Bene-Bac Plus Powder Canada",
        "Bener ProRed-10",
        "Bener ProRed-30",
        "BenzaPen 48 Injectable Suspension",
        "Benzoyl Peroxide Creme Rinse",
        "Benzoyl Peroxide Shampoo",
        "Berrier Hip & Joint Soft Chews for Cats",
        "Berrier Hip & Joint Soft Chews for Dogs",
        "Beta Mos",
        "Betacillin Drops",
        "Betacillin Tablets",
        "Betadine Solution",
        "Betadine Surgical Scrub",
        "Betagen Topical Spray",
        "BetaVet",
        "Beuthanasia-D Special",
        "C.E.T. IntelliDent Cat Bites Canada",
        "C.E.T. Oral Hygiene Rinse",
        "C.E.T. VeggieDent Flex + Joint Health Tartar Control Chews for Dogs",
        "C.E.T. VeggieDent FR3SH",
        "C.E.T. VeggieDent FR3SH Canada",
        "C.E.T. VeggieDent Zen + L-Theanine Tartar Control Chews for Dogs",
        "C.E.T. VeggieDent Zen + L-Theanine Tartar Control Chews for Dogs Canada",
        "Caco-Iron-Copper Solution Canada",
        "Cai-Pan Mint Canada",
        "Cal Dex 842",
        "Cal Dex CMPK Injection",
        "Cal Dex Special 1100",
        "Cal-Mag Plus Canada",
        "Cal-Mag-Co Gel",
        "Cal-Mag-SE Gel",
        "Cal-MPK 1080 Injection",
        "Cal-Nate 1069",
        "Cal-Paste Plus Canada",
        "Cal-Phos #2 with Potassium Injection",
        "Cal-Phos Suspension",
        "Cal-Plex Forte",
        "Cal-Plus Canada",
        "Calboro-23% Canada",
        "CalCaps",
        "CalciBind",
        "CalciCure",
        "CalciCure HP Gel",
        "Calciphos",
        "CALF ABC Paste Canada",
        "Calf BaseLyte",
        "Calf BYCEPS 'B'",
        "Calf Claim",
        "Calf Claim Canada",
        "Calf Gel 95",
        "Calf GoldLyte",
        "Calf Milk Replacer",
        "Calf Perk",
        "Calf Perk Canada",
        "Calf preRD",
        "Calf Quencher",
        "Calf Renova",
        "Calf Renova Canada",
        "Calf Restart One-4",
        "Calf Scour Bolus",
        "Calf Scour Bolus Canada",
        "Calf Solutions 21-18 Whole Milk Extender",
        "Calf Solutions BalanSure",
        "Calf Solutions BalanSure Medicated",
        "Calf Solutions BalanSure Medicated with Clarifly Larvicide",
        "Calf Solutions KCAL",
        "Calf Solutions Scours & Pneumonia Treatment Concentrate Medicated",
        "Calf Solutions TheraCaf Plus",
        "Calf Solutions Ultra Start 150",
        "Calf Solutions Ultra Start 150 Plus",
        "Calf Solutions Whole Milk AddVantage Medicated",
        "Calf Solutions Whole Milk AddVantage Medicated with ClariFly Larvicide",
        "Calf-Guard",
        "Calf-Guard Canada",
        "D-128",
        "D-256",
        "D-Horn Paste",
        "D-Horn Paste Canada",
        "d-l-Methionine Powder",
        "d-Panthenol",
        "D-Panthenol 25%",
        "d-Panthenol Injection",
        "D-Ribose Canada",
        "D-Stress Canada",
        "D-Tec CB",
        "D-Thrush",
        "D-Worm Combo Flavored Chewables for Medium & Large Dogs",
        "D-Worm Combo Flavored Chewables for Puppies & Small Dogs",
        "D-Worm Dog Dewormer Chewable Tablets for Large Dogs",
        "D-Worm Dog Dewormer Chewable Tablets for Puppies & Small Dogs",
        "D-Worm Dog Dewormer Tablets for Large Dogs",
        "D-Worm Dog Dewormer Tablets for Puppies & Small Dogs",
        "D'Limonene Fragrance Dip & Shampoo Additive",
        "D'Limonene Shampoo",
        "Daily Health Canine Chewable Tablets",
        "Dairy & Beef Nutri-Drench",
        "Dairy Bomb 55Z",
        "Dairy Bomb-55",
        "Dairy Cal Bolus",
        "Dairy Dine Canada",
        "Dairy Lamb-Gro Lamb Milk Replacer Canada",
        "Dairy Prep Wipes Canada",
        "Dairyman's Defence 3/4 Guard Canada",
        "Dairyman's Defence Combat Canada",
        "Dairyman's Defence First Defence Canada",
        "Dairyman's Defence Premier Canada",
        "Dairyman's Defence Shield Canada",
        "Dairyman's Defence Ultra Canada",
        "Dakil S Disinfectant",
        "Dandelion Leaf Canada",
        "Dariclox",
        "Dark Horse Nu-Image Canada",
        "Darlex Insecticide",
        "Dasuquin Advanced For Cats of All Sizes",
        "Dasuquin Advanced For Large Dogs",
        "Dasuquin Advanced For Small to Medium Dogs",
        "Dasuquin Advanced Soft Chews for Cats",
        "Dasuquin Advanced Soft Chews For Large Dogs",
        "Dasuquin Advanced Soft Chews For Small to Medium Dogs",
        "Dasuquin Advanced Soft Chews with Egg Shell Membrane for Large Dogs",
        "Dasuquin Advanced Soft Chews with Egg Shell Membrane for Small to Medium Dogs",
        "Dasuquin Chewable Tablets For Large Dogs Canada",
        "Dasuquin Chewable Tablets For Small to Medium Dogs Canada",
        "Dasuquin For Cats",
        "Dasuquin For Cats Canada",
        "Dasuquin For Large Dogs",
        "Dasuquin For Small to Medium Dogs",
        "Dasuquin Soft Chews for Cats",
        "Dasuquin Soft Chews For Large Dogs",
        "Dasuquin Soft Chews For Large Dogs Canada",
        "Dasuquin Soft Chews For Small to Medium Dogs",
        "Dasuquin Soft Chews For Small to Medium Dogs Canada",
        "Dasuquin with MSM Chewable Tablets For Large Dogs Canada",
        "Dasuquin with MSM Chewable Tablets For Small to Medium Dogs Canada",
        "Dasuquin With MSM For Large Dogs",
        "Dasuquin With MSM For Small to Medium Dogs",
        "Dasuquin With MSM Soft Chews For Large Dogs",
        "Dasuquin With MSM Soft Chews For Large Dogs Canada",
        "Dasuquin With MSM Soft Chews For Small to Medium Dogs",
        "E & Selenium",
        "E Lytes Plus Canada",
        "E Plus Canada",
        "E Plus Powder Canada",
        "E Sel Canada",
        "E Sel P Canada",
        "E Sel S Canada",
        "E-5000",
        "E-SE",
        "E-Se Injectable Canada",
        "E-Z Mobility Canada",
        "E-Z Rest Canada",
        "E.D.D.I. 20 Gr. (Dextrose Base)",
        "E.D.D.I. 20 Gr. (Organic Iodine Salt)",
        "E.D.D.I. 20 Gr. (Salt)",
        "E.D.D.I. 40 Gr. (Salt)",
        "Ear Cleaner for Dogs & Cats",
        "Ear Cleansing Solution",
        "Ear Cleansing Solution Canada",
        "Ear Flushing Drying Lotion",
        "Ear Mite Lotion",
        "Ear Rite Miticide For Cats & Kittens",
        "Ear Wash with Tea Tree Oil For Dogs & Cats",
        "Ear-Rite Insecticidal Ear Wash",
        "EarMed Boracetic Flush",
        "EarMed Cleansing Solution & Wash",
        "EarMed Mite Lotion",
        "EarMed Powder",
        "EarMed Pro Cleanse",
        "EarMed Wipes",
        "Ease-Derm Omega Chews For Cats and Small Dogs Canada",
        "Ease-Derm Omega Chews For Medium and Large Dogs Canada",
        "Ease-Flex Soft Chews for Cats Canada",
        "Ease-Flow for Cats Canada",
        "EASOTIC Miconazole, Gentamicin and Hydrocortisone Aceponate Otic Suspension Canada",
        "easOtic Otic Suspension",
        "Easy Does It Canada",
        "Easypack Hoof Packing Canada",
        "Easywillow Canada",
        "EAZI-Breed CIDR Cattle Insert",
        "EAZI-Breed CIDR Sheep Insert",
        "Econo Pak",
        "Ecovet Fly Repellent",
        "Ectiban 25 Fly Killer Canada",
        "EctoShield Topical Solution Extra Large Dog Canada",
        "EctoShield Topical Solution Large Dog Canada",
        "EctoShield Topical Solution Medium and Large Cat Canada",
        "EctoShield Topical Solution Medium Dog Canada",
        "EctoShield Topical Solution Small Cat Canada",
        "EctoShield Topical Solution Small Dog Canada",
        "Edema Vac 100",
        "Edema Vac 100 Canada",
        "Edema Vac 500",
        "Edema Vac 500 Canada",
        "EFA1N",
        "EFA2N",
        "EFA3N",
        "EfaLyt Hypoallergenic Creme Rinse",
        "EfaLyt Hypoallergenic Shampoo",
        "EfferCept",
        "EfferCeptSG",
        "EfferSan",
        "EFFIPRO PLUS Topical Solution for Cats",
        "EFFITIX Topical Solution for Dogs",
        "Effol Winter Hoof Gel Canada",
        "Effortless HA",
        "EFICUR Canada",
        "Egg Boost",
        "Egusin 250",
        "Egusin SLH",
        "EIA AGID Test Kit",
        "Eicosa3FF SnipCaps (Large Caps)",
        "Eicosa3FF SnipCaps (Small Caps)",
        "Eicosa3FF SnipCaps Large Canada",
        "Eicosa3FF SnipCaps Small Canada",
        "EicosaCaps Omega 3 & 6 Capsules S Canada",
        "EicosaCaps Omega 3 & 6 Capsules Sm",
        "EicosaDerm Omega 3 Liquid",
        "EicosaDerm Omega 3 Liquid Canada",
        "Elector PSP Premise Insect Control Agent",
        "Electra Caps Canada",
        "Electras Canada",
        "Electro Dex",
        "Electro Gel",
        "Electro-Plex Oral Supplement",
        "Electrolyt 7 Canada",
        "Electrolyte Gold Canada",
        "Electrolyte Infusion Canada",
        "Electrolyte Solution with Dextrose"
    ],
    Pigs: [
        
        "Aksai Black Pied pig",
        "American Landrace",
        "American Yorkshire",
        "Angeln Saddleback",
        "Ankamali pig",
        "Apulo-Calabrese",
        "Arapawa pig",
        "Auckland Island pig",
        "Australian Yorkshire",
        "Ba Xuyen",
        "Basque pig",
        "Bazna pig",
        "Beijing Black",
        "Belarus Black Pied pig",
        "Belgian Landrace",
        "Bentheim Black Pied pig",
        "Berkshire pig",
        "Black Iberian pig",
        "Breitovo",
        "British Landrace pig",
        "British Lop",
        "British Saddleback",
        "Bulgarian White",
        "Casertana pig",
        "Celtic pig",
        "Chato Murciano",
        "Chester White",
        "Choctaw Hog",
        "Cinta Senese",
        "Creole pig",
        "Cumberland pig",
        "Danish Landrace pig",
        "Danish Protest Pig",
        "Dorset Gold Tip",
        "Duroc Italiana",
        "Duroc pig",
        "Dutch Landrace pig",
        "Essex pig",
        "Estonian Bacon pig",
        "Fengjing pig",
        "Forest Mountain pig",
        "Gascon pig",
        "Gloucestershire Old Spots",
        "Göttingen minipig",
        "Grice",
        "Guinea Hog",
        "Hampshire pig",
        "Hereford pig",
        "Italian Landrace",
        "Jeju Black pig",
        "Kagoshima Berkshire",
        "Kakhetian pig",
        "Kemerovo pig",
        "Korean Native pig",
        "Krškopolje pig",
        "Kunekune",
        "Lacombe pig",
        "Landrace pig",
        "Large Black pig",
        "Large White Italiana",
        "Large White pig",
        "Large White Ulster pig",
        "Latvian White pig",
        "Lincolnshire Curly Coat",
        "Lithuanian Native pig",
        "Lithuanian White",
        "Livny pig",
        "Mangalica",
        "Meidam",
        "Meishan pig",
        "Mexican Creole hairless pig",
        "Middle White",
        "Miniature pig",
        "Mora Romagnola",
        "Mukota",
        "Mulefoot",
        "Myrhorod pig",
        "Nero di Parma",
        "Nero Siciliano",
        "North Caucasian pig",
        "North Siberian pig",
        "Ossabaw Island Hog",
        "Oxford Sandy and Black",
        "Piétrain",
        "Poland China",
        "Red Wattle Hog",
        "Sarda pig",
        "Semirechensk",
        "Siberian Black Pied",
        "Small Black pig",
        "Small White pig",
        "Swabian-Hall swine",
        "Swedish Landrace pig",
        "Taihu pig",
        "Tamworth pig",
        "Tokyo-X",
        "Tsivilsk pig",
        "Turopolje pig",
        "Ukrainian Spotted Steppe",
        "Ukrainian White Steppe",
        "Urzhum pig",
        "Vietnamese Pot-bellied",
        "Welsh pig",
        "Wessex Saddleback",
        "Yorkshire Blue and White"
    ],
    Ferrets: [
        "Albino",
        "Black Sable",
        "Black Sable Mitts",
        "Regular Sable",
        "Regular Sable Mitts",
        "Blaze",
        "Champagne",
        "Chocolate",
        "Chocolate Mitts",
        "Cinnamon",
        "Cinnamon Mitts",
        "Dalmatian",
        "Heavy Silver or Pewter",
        "Panda",
        "Light pattern",
        "Medium pattern",
        "Siamese",
        "Siamese Mitts",
        "Striped White",
        "Dark-eyed White"
    ],
    Rodents: [
        "Genus Bathyergus",
        "Bathyergus janetta",
        "Bathyergus suillus",
        "Genus Cryptomys",
        "Cryptomys bocagei",
        "Cryptomys damarensis",
        "Cryptomys foxi",
        "Cryptomys hottentotus",
        "Cryptomys mechowi",
        "Cryptomys ochraceocinereus",
        "Cryptomys zechi",
        "Genus Fukomys",
        "Fukomys amatus",
        "Fukomys anselli",
        "Fukomys bocagei",
        "Fukomys damarensis",
        "Fukomys darlingi",
        "Fukomys foxi",
        "Fukomys ilariae",
        "Fukomys kafuensis",
        "Fukomys mechowii",
        "Fukomys micklemi",
        "Fukomys occlusus",
        "Fukomys ochraceocinereus",
        "Fukomys whytei",
        "Fukomys zechi",
        "Genus Georychus",
        "Georychus capensis ",
        "Genus Heliophobius",
        "Heliophobius argenteocinereus",
        "Genus Heterocephalus",
        "Heterocephalus glaber",
        "Genus Atherurus",
        "African brush-tailed porcupine",
        "Asiatic brush-tailed porcupine",
        "Genus Hystrix",
        "Thick-spined porcupine",
        "Philippine porcupine",
        "Sumatran porcupine",
        "Malayan porcupine",
        "Sunda porcupine",
        "Cape porcupine",
        "Crested porcupine",
        "Indian porcupine",
        "Genus Trichys",
        "Long-tailed porcupine",
        "Genus Coendou",
        "Bicolored-spined porcupine",
        "Streaked dwarf porcupine",
        "Bahia porcupine",
        "Black-tailed hairy dwarf porcupine",
        "Mexican hairy dwarf porcupine",
        "Black dwarf porcupine",
        "Brazilian porcupine",
        "Frosted hairy dwarf porcupine",
        "Roosmalen's dwarf porcupine",
        "Rothschild's porcupine",
        "Stump-tailed porcupine",
        "Paraguaian hairy dwarf porcupine",
        "Brown hairy dwarf porcupine",
        "Genus Erethizon",
        "North American porcupine",
        "Genus Chinchilla",
        "Long-tailed chinchilla",
        "Short-tailed chinchilla",
        "Genus Lagidium",
        "Northern viscacha",
        "Southern viscacha",
        "Wolffsohn's viscacha",
        "Genus Lagostomus",
        "Plains viscacha",
        "Genus Cavia",
        "Brazilian guinea pig",
        "Shiny guinea pig",
        "Santa Catarina's guinea pig",
        "Greater guinea pig",
        "Domestic guinea pig",
        "Montane guinea pig",
        "Genus Galea",
        "Brandt's yellow-toothed cavy",
        "Common yellow-toothed cavy",
        "Spix's yellow-toothed cavy",
        "Genus Microcavia",
        "Southern mountain cavy",
        "Andean mountain cavy",
        "Shipton's mountain cavy",
        "Genus Dasyprocta",
        "Azara's agouti",
        "Coiban agouti",
        "Crested agouti",
        "Black agouti",
        "Orinoco agouti",
        "Kalinowski agouti",
        "Red-rumped agouti",
        "Mexican agouti",
        "Black-rumped agouti",
        "Central American agouti",
        "Ruatan Island agouti",
        "Genus Myoprocta",
        "Green acouchi",
        "Red acouchi",
        "Genus Cuniculus",
        "Lowland paca",
        "Mountain paca",
        "Genus Ctenomys",
        "Argentine tuco-tuco",
        "Southern tuco-tuco",
        "Azara's tuco-tuco",
        "Bolivian tuco-tuco",
        "Bonetto's tuco-tuco",
        "Brazilian tuco-tuco",
        "Colburn's tuco-tuco",
        "Conover's tuco-tuco",
        "Chacoan tuco-tuco",
        "Emily's tuco-tuco",
        "Reddish tuco-tuco",
        "Tawny tuco-tuco",
        "Haig's tuco-tuco",
        "Catamarca tuco-tuco",
        "Mottled tuco-tuco",
        "White-toothed tuco-tuco",
        "Lewis' tuco-tuco",
        "Magellanic tuco-tuco",
        "Maule tuco-tuco",
        "Mendoza tuco-tuco",
        "Tiny tuco-tuco",
        "Natterer's tuco-tuco",
        "Furtive tuco-tuco",
        "Highland tuco-tuco",
        "Pearson's tuco-tuco",
        "Goya tuco-tuco",
        "Peruvian tuco-tuco",
        "San Luis tuco-tuco",
        "Porteous' tuco-tuco",
        "Rio Negro tuco-tuco",
        "Salta tuco-tuco",
        "Silky tuco-tuco",
        "Social tuco-tuco",
        "Steinbach's tuco-tuco",
        "Talas tuco-tuco",
        "Collared tuco-tuco",
        "Robust tuco-tuco",
        "Tucuman tuco-tuco",
        "Strong tuco-tuco",
        "Genus Aconaemys",
        "Chilean rock rat",
        "Aconaemys porteri",
        "Sage's rock rat",
        "Genus Octodon",
        "Bridge's degu",
        "Common degu",
        "Moon-toothed degu",
        "Isla Mocha degu",
        "Genus Octodontomys",
        "Mountain degu",
        "Genus Octomys",
        "Mountain viscacha-rat",
        "Genus Pipanacoctomys",
        "Golden viscacha-rat",
        "Genus Salinoctomys",
        "Los Chalchaleros' viscacha-rat",
        "Genus Spalacopus",
        "Coruro",
        "Genus Tympanoctomys",
        "Plains viscacha-rat",
        "Genus Abrocoma",
        "Bennett's chinchilla rat",
        "Bolivian chinchilla rat",
        "Budin's chinchilla rat, A. budini",
        "Ashy chinchilla rat",
        "Famatina chinchilla rat",
        "Abrocoma schistacea",
        "Uspallata chinchilla rat",
        "Punta de Vacas chinchilla rat",
        "Genus Cuscomys",
        "Cuscomys ashanika",
        "Genus Dactylomys",
        "Dactylomys boliviensis",
        "Dactylomys dactylinus",
        "Dactylomys peruanus",
        "Genus Kannabateomys",
        "Kannabateomys amblyonyx",
        "Genus Olallamys",
        "Olallamys albicauda",
        "Olallamys edax"
    ],
    VetClinicals: [
        "The Cat Hospital",
        "The Vet Spectrum",
        "Pet’s Best Vet Clinic",
        "Harmony for Animals",
        "Refuge Village Veterinary",
        "Scottsdale Vets",
        "Vet Groom",
        "Well Pets Veterinary Care",
        "The Cat & Paw Clinic",
        "FastMed Urgent Care",
        "BestCare Animal Hospital",
        "Rural Vets",
        "Just 4 Cats",
        "Trusty Pets Animal Veterinary Clinic",
        "Priority Pet Clinic",
        "GoodVets Uptown",
        "Refuge Pets Animal Hospital",
        "Caribou Rental Vet",
        "Camelback Vets",
        "Vet Specialty & Surgical Services",
        "All Kinds of Heros",
        "Happy Horse Hospital",
        "ArchPaw Veterinary & Animal Hospital",
        "Aspiring Veterinary Services",
        "The DVM Office",
        "Care Vet",
        "Hill Country Veterinary Hospital",
        "Veterinary Edge",
        "DrPawPaw",
        "VCA Animal Clinic",
        "AZ Animal Resort",
        "Friendly Animal Hospital",
        "Washburn Equine",
        "All about Puppy Care",
        "Creature Comforts Clinic and Surgical Center",
        "K9 Pooch Service",
        "Lincoln Ridge Dental",
        "Healthy Paws Animal Veterinary Clinic",
        "Integrity Animal Care",
        "Goodwill Vet Clinic",
        "Fauna Animal Care & Therapy",
        "Cahill Animal Hospital",
        "Sunbury Veterinary Clinic",
        "Healthy Standard Of Care Animal Hospital",
        "1 Pet Resort",
        "Very Good Veterinarians",
        "Neona Arch Animal Hospital",
        "Animales Animales",
        "Crystal Mountain Animal Hospital",
        "Pet Life Animal Hospital",
        "Clinicats",
        "Banfield Pet Hospital",
        "The Heel Animal Hospital",
        "AllPet Healing",
        "Vet Med Services",
        "Paw Passion Your Pets Animal Clinic",
        "Lucky White Vet",
        "All Pet Vet Services",
        "DoctorBliss",
        "Charlie’s Pet Care",
        "Homewatch EAS",
        "CutePaw: Total Pet Health",
        "Austin Vet Care",
        "Wild West Vet",
        "Lil Pet Animal Clinic",
        "Sciulli Svetronika",
        "Globetrotter Animal Hospital",
        "Amity Animal Hospital",
        "Vetcall Animal Hospital",
        "Feline Frenzy",
        "Wide Valley",
        "Pet Clinic of Tempe",
        "National Veterinary Care",
        "Mo West",
        "Heal Veterinary Clinic",
        "A Plus Plus Vet",
        "Orion Animal Clinic",
        "After Hours Vet Clinic",
        "Empower Cat Clinic",
        "Even Port Animal Hospital",
        "Cruisin’ Pets Hospital",
        "The Pet Doctors",
        "Amelyn Animal Hospital",
        "Best in Show Vets",
        "Pray It With Love",
        "Stanford Animal Clinic",
        "Crazy Cat Clinic",
        "Exceptional Vets Co.",
        "Greaton Animal Hospital",
        "The AnimalCures",
        "Pawn1st Dog Clinic",
        "Wide Way",
        "Bella Wild Rabbit",
        "Horse’s Kingdom Vet",
        "Happy Pets Animal Hospital",
        "Furever Vets",
        "A Friendly Vet",
        "Pet Panorama",
        "Dogwood Animal Clinic",
        "Animates Vetcare Clinic",
        "Sandberg Animal Hospital",
        "Small Animal Veterinary Centre",
        "Trusty Pet Hospital",
        "Health fest",
        "Escape Vet",
        "Vet Cat Clinic",
        "Victor Wood",
        "Mobile Veterinary Clinic",
        "MedVet",
        "Pet Nest Animal Hospital",
        "Prime Days Pets",
        "Urban Pet Healthcare",
        "Animal Bliss Animal Clinic",
        "Recovery Pet Clinic",
        "Petfectionn",
        "Treat Hope",
        "Health4Life Veterinarians",
        "Good Cat Practice",
        "Lorenzo Animal Hospital",
        "White Rock Veterinary",
        "Diva Dental Care",
        "West Berg Animal Clinic",
        "West Loop Veterinary Care",
        "Animal Smile Vet",
        "Elite East Animal Hospital",
        "Crestview Veterinary Clinic",
        "Athena’s Paws Clinic",
        "Rosewood Vets",
        "Dog Priority Clinic",
        "Feline Care Clinic",
        "Pet Metz Animal Hospital",
        "Moving Forward Veterinarians",
        "Cats Love Housecalls",
        "Health Hill",
        "Piper Street Vet Clinic",
        "Northlands Animal Care Hospital",
        "Zing Crest",
        "Vet’s Choice Pals",
        "North Shore Veterinary Clinic",
        "Animal Help",
        "Sunset Veterinary Clinic",
        "The Pet Uclick",
        "Pet Space Animal Hospital",
        "Bird Vet Clinic",
        "Lovestock and Home",
        "Wills Berry",
        "Royal Crest Vet Clinic",
        "Seeming Veterinary Clinic",
        "New life Animal Hospital",
        "Veterinareurs",
        "ApexpetCare",
        "Planet Pets",
        "Totally Vets",
        "Pet-tastic Care",
        "Sky Pets Animal Hospital",
        "Treatment Pet Clinic",
        "Happy Paws",
        "Crazy Pans",
        "Firehouse Animal Health Center",
        "Paws and Claws Veterinary Clinic",
        "Coastal Bay Animal Clinic",
        "Animal Emergency & Referral Centre",
        "PAWS Medical Center",
        "Pet Essen Animal Hospital",
        "Victoria Veterinary center",
        "Pet Animal Hospitals",
        "White Wave Animal Clinic",
        "Healthy Bones Co.",
        "Animal Welfare",
        "Safe Crew Animal Hospital",
        "Vets North",
        "Cat Care Clinic",
        "Happy Grid Animal Clinic",
        "Hospitalizing Cats",
        "Animal and Bird Hospital",
        "Health Quest Animal Clinic",
        "A Cat’s All That",
        "Elite Vet",
        "Puppy Comfy Animal Clinic",
        "Veterinary Partners",
        "Morning Veterinary Centre",
        "New Crest Animal Hospital",
        "Vet Around Town",
        "Beautiful Pets Boutique",
        "Animal Curves Animal Clinic",
        "Happy Paws Veterinarians",
        "Heritage Veterinary Clinic",
        "Healing Shades",
        "First Vets",
        "Andy’s Veterinary Clinic",
        "Wood Wings Animal Hospital",
        "Animal Center Vet",
        "Street Veterinary Clinic",
        "Aeroben Pups",
        "Animal Emergency & Treatment Centers",
        "The PawProtectors",
        "Heal Motto",
        "Small Animal Clinic",
        "Paw Priority",
        "Saving Hands Animal Hospital",
        "Caspian Vet",
        "Republic Veterinary Hospital",
        "Spring Berg",
        "Veterinary Ctr",
        "Vet Farm & Pet Clinic.",
        "Star Eager Animal Clinic",
        "GoodVets West Loop",
        "Peterinarians",
        "Health Track",
        "Pet Health Centre",
        "Cowell Veterinary Clinic",
        "Trinity Animal Clinic",
        "The Pet Priority",
        "Pets First",
        "Cosmix Animal Hospital",
        "Pear Pet Vaccines",
        "The WellPets",
        "Healo fly Animal Clinic",
        "My Pet Clinic",
        "A+ Cattery",
        "Wynk Way Animal Clinic",
        "Newtown Pet Clinic",
        "The Pet Practice",
        "Pet Circle Animal Hospital",
        "Goal Vet Clinic",
        "Las Vegas Wild Vet",
        "Med fix Animal Hospital",
        "A Cat’s Life",
        "Bat City Mobile Vet Care",
        "White Safe Animal Clinic",
        "Dogs & Cats First",
        "Holistic Vets",
        "Happy Graphy",
        "Wild Companion Vet",
        "Vets One",
        "Heal Master Animal Hospital",
        "Goodland Veterinary Clinic",
        "Road Vet Clinic",
        "Pet Quest Animal Clinic",
        "Vet For Your Pets",
        "Capital Veterinary Clinic",
        "Pet Presto Animal Hospital",
        "CritterAide",
        "Paradise Valley Vet",
        "Prime Stone",
        "VetCare Finance",
        "Feel Healed Vets",
        "Urban Pets",
        "Horse’s Haven Vet Clinic",
        "Preventive Vet",
        "Marvello Animal Hospital",
        "Animated Animal Doctors",
        "Vets4Pets",
        "Austin Animal Hospital",
        "Pathway Vet Alliance",
        "The Cat Clinic",
        "Fusion Paws",
        "Vetlife Twizel",
        "Victory Vets",
        "Peto Flex Animal Clinic",
        "Whistler Veterinary",
        "A & B Pet Care",
        "Alright Animal Hospital",
        "Peak’s Animal Clinic",
        "Your friendly vet",
        "Well Ware",
        "Wild Pet Desert",
        "Louisville Vet",
        "North Bay Animal Clinic",
        "Cattle And Bull",
        "C & A Veterinarian",
        "Healo Right",
        "Memorial Avenue Vet Clinic",
        "Rosedale Veterinary Clinic",
        "Aroma Animal Hospital",
        "Humanimals",
        "Trusted Vets Co.",
        "Stepex Animal Clinic",
        "Animals for Animals",
        "D&E Veterinary",
        "Servo Sense",
        "Pet Place",
        "Pet Health Group",
        "Pet Trail Animal Hospital",
        "Hank’s Pet Clinic",
        "Bee Cave Veterinary Clinic",
        "Vet About Town",
        "Vetuoso",
        "Sawyer’s Vet Clinic",
        "Fix It Veterinary Clinic",
        "Acute Companion Veterinary Clinic",
        "Animal First Clinic",
        "Greenway Street Vet",
        "Companion Care Clinic",
        "Mayfair Animal Clinic",
        "Vet-It up Clinic",
        "Fine Vision Vet Clinic",
        "Cool Creatures",
        "Flying High Veterinarian",
        "slice a mice",
        "Magic Paws",
        "Animaleon",
        "Comfortreatment Pet Clinic",
        "Pawing Packs",
        "Love Pet Hospital",
        "Gerbil Town",
        "Animal House",
        "Feline Fetch",
        "Fauna Vet Clinic",
        "Creature Comforts",
        "Oliver Animal Hospital",
        "DoctorWell",
        "Giga Pet Clinic",
        "Petcare Vet Clinic",
        "Gratus Animal Hospital",
        "Puppy Love",
        "Handy Veterinary Clinic & Hospital",
        "Profound Vet Services",
        "Pet Life Care",
        "Delta Animal Hospital",
        "The Total Pet",
        "Comfort Treatment",
        "Meline’s Home",
        "Trustivet",
        "Precise Vet Clinic",
        "Far West Veterinary Clinic",
        "ReliaCare Veterinary",
        "Companion Care Vets",
        "Broadway Animal Hospital",
        "Best Friend Animal Hospital",
        "Veterinary Surgeons",
        "Canine Health Clinic",
        "Animal Medic Animal Veterinary Clinic",
        "White House Vets",
        "Four Paws At Four Points",
        "PawPawsRx",
        "Animal Health Agency",
        "Royal Crest Veterinary Clinic",
        "The TrueHeel Animal Hospital",
        "VetPartners",
        "Exclusive Cats Vet",
        "Safe Haven Pet Hospital",
        "Midlands Veterinary",
        "Healthy Cats Clinic",
        "Li’l Pet Animal Clinic",
        "Baken Animal Clinic",
        "Five Star Veterinary Center",
        "Caring Claws Veterinary Clinic",
        "Disease Control",
        "Pioneering Vet",
        "Reliant Care Animal Hospital",
        "Equine Pets Hospital",
        "Wash-A-Dog Vetcare",
        "Rodentville",
        "Animal Care Company",
        "Netanya Clinic",
        "Paw Prints Animal Veterinary Clinic",
        "All Paws Veterinary",
        "The VAM Clinic",
        "DoWell Animal Veterinary Clinic",
        "Sea Point Veterinary Company",
        "Cross Vet Surry Hills",
        "My Pet Place Animal Hospital",
        "Avonhead Vets",
        "Pet Care Collective",
        "Mighty Paws Veterinary Clinic",
        "Habitat Boarding Cattery",
        "The Pawsy Vet",
        "Trusty Tails Animal Veterinary Clinic",
        "Critter Care",
        "Tick n Tock Clinic",
        "Unconditional Love Animal Hospital",
        "Frankford Animal Clinic",
        "Truly Animal Health",
        "Petite Care Animal Clinic",
        "Pet Health Center",
        "Prime Vet Centre",
        "ProLife Pet Care",
        "Dog And Cat Hospital",
        "Duke Animal Hospital",
        "Pet Well Animal Clinic",
        "Sunrise Pet Clinic",
        "Melton Veterinary Clinic",
        "Fauna Animal Health Boutique",
        "Care Vets Bridgend",
        "Premier Veterinary Group",
        "Mother Goose Animal Clinic",
        "Veterinary Distributors",
        "VCA North Scottsdale",
        "Fauna Healthcare & Surgery",
        "Health Animal Rescue",
        "Eagle Eye Clinic",
        "Vet Precision Clinic & Surgery",
        "Animal Medical Center",
        "The Paw Clinic",
        "Quality Animal Care",
        "Woodsprings Pets Clinic",
        "Animal Options Vet Clinic",
        "Supreme Vet Care",
        "New Canton",
        "Hoppy Healers",
        "WonderFULLcare Animal Hospital",
        "Vet Mobile Services",
        "Happy Pets Vets",
        "Assurant Care Veterinary",
        "Wide Way Animal Rescue",
        "Noble Veterinary Surgeons",
        "Newon Care Veterinary Clinic and Animal Hospital",
        "Beacon Veterinary Specialists",
        "Great South Vets",
        "FluffyPets Veterinary Clinic",
        "Valley Veterinary Clinic",
        "Block House Animal Hospital",
        "MorePet Animal Hospital",
        "Animal Eye Care",
        "Dog Bones Co.",
        "CareVibe Animal Health Solutions",
        "Animal Discount Clinic",
        "Your Veterinarian",
        "Pet Life Veterinary Care",
        "Pets Pharmacy",
        "Pet Doctors Botany",
        "VeterinaryVitality",
        "Medilink Labs",
        "Riverside Veterinary Clinic",
        "Four Legacy",
        "Happy Animal Hospital",
        "The Wild Vet",
        "Trusted Pets Clinic",
        "VetFriends Animal Hospital",
        "Affordable Pet Care",
        "All Creatures animal veterinary clinic",
        "Healthy Prints Animal Veterinary Clinic",
        "Avalon Animal Clinic",
        "Lil Paws+",
        "Little Cutes",
        "Treatment Target",
        "Healthy Tails Animal Veterinary Clinic",
        "TrustedHands Vet Clinic",
        "Linda’s Home Health",
        "Halo Pet Care & Veterinary",
        "Doctor Dolittle",
        "Clare Animal Health",
        "Precise Vet Services",
        "GoodHands Pet Clinic",
        "Cheery Cat Clinic",
        "Reliable Vet Companion",
        "Hairy Godmother Pet Hospital",
        "Back To Cat Clinic",
        "Fauna Vet Boutique",
        "Faithful Companions Veterinary Hospital",
        "Student Veterinary Clinic",
        "Vetmedics Canada",
        "Angel Touch Veterinarian",
        "Vet To Your Door",
        "Buttercup Veterinary Hospital",
        "Warkworth Vets",
        "Vetaid Veterinary Services",
        "City Pet Animal Hospital",
        "Nature’s Paws",
        "Lakeside Vet Clinic",
        "Green Island Veterinary Clinic",
        "Vet Health & Surgical Clinic",
        "Animals’ Haven",
        "Green Bay Veterinary Clinic",
        "Veterinary Boutique",
        "Cat Vet Clinic",
        "Veterinary Growth Partners",
        "Trusty Paws Animal Veterinary Clinic",
        "York Vet Clinic",
        "Royal Oak Veterinary Care",
        "Natures Friends Animal Veterinary Clinic",
        "Animals First Veterinarians",
        "The Bizarro Vet",
        "A Pet’s Best Vet",
        "VetHelp",
        "South Veterinary",
        "Animals Choice Hospital",
        "Sun Veterinarians",
        "Vet on Call",
        "Profound Vet Clinic",
        "All About The Cats",
        "Vet Pest Control",
        "PetsBest Clinic",
        "Small Five Vet Clinic Limited",
        "Sky Pets Vets",
        "All Critters",
        "Dog & Cat First Vet",
        "Oak Street Veterinary",
        "Pet Friend",
        "Vet-Euphoria",
        "Phoenix Cat Clinic",
        "Pet Medic Animal Veterinary Clinic",
        "Four Paws Veterinary Hospital",
        "Small Animal Specialist Hospital",
        "beLOVEd Animal Hospital",
        "CareVets",
        "Animal Dermatology Clinic",
        "Tails Wag Veterinary Clinic",
        "Meow Medical Center",
        "Murrays Veterinary Clinic",
        "The Animal Boutique",
        "Las Vegas Cat Clinic",
        "Pet Clinic Of Nevada",
        "FitLife Veterinary",
        "Pet Loss Specialists",
    ]
}